---
title: "Owner Analysis"
format: html
name: Ian Lee
---

## Exercise: Explore, Clean, and Wrangle Data

## Quarto

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

## Read in data
```{r}
lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv")
```

## Replace -99999 with NA values
```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))
# To get unique values from a column named 'column_name'
unique(lobster_abundance$SIZE_MM)
```

## Filter out Naples Reef data
```{r}
not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")
unique(lobster_abundance$SITE)
```

## Filter Arroyo Quemado lobsters
```{r}
aque_70mm <- lobster_abundance %>% 
    filter(SITE == "AQUE" & SIZE_MM >= 70)
aque_70mm
```

## Exercise: Data Visualization
```{r}
hist_plot <- ggplot(data = lobster_abundance, aes(x = SIZE_MM)) +
  geom_histogram(fill = "skyblue", color = "black") +
  facet_wrap(~SITE)
hist_plot

ggsave("../figs/lobster_hist.png", plot = hist_plot, width = 10, height = 6)
```

## Total # of lobsters observed
```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>%
  mutate(LOBSTER_COLOR = "red") %>% 
  summarize(COUNT = n())
lobsters_summarize
```

# Line and point plots
```{r}
# line plot
line_plot <-ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_line(aes(color = SITE)) 
line_plot

ggsave("../figs/line_plot.png", plot = line_plot, width = 10, height = 6)

# line and point plot
line_point_plot <-ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) 
line_point_plot

ggsave("../figs/line_point_plot.png", plot = line_point_plot, width = 10, height = 6)
```

## Designate marine protected areas (MPAs)
```{r}
lobster_mpa <- lobster_abundance %>% 
    mutate(DESIGNATION = case_when(
    SITE %in% c("IVEE", "NAPL") ~ "MPA",
    SITE %in% c("AQUE", "CARP", "MOHK") ~ "not MPA"
  ))
head(lobster_mpa, 10)
```

